dist: trusty
language: php
php:
  - 7.0

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - NODE_JS_VERSION=6
  matrix:
    - TEST_SUITE=marketplace_review

matric:
  include:
    - language: node_js
    - node_js: 6
    - env: TEST_SUITE=editorconfig



before_install:
  - test -n "$TRAVIS_PHP_VERSION" && test -n "$GITHUB_TOKEN" && echo "Found GitHub token" && composer config github-oauth.github.com "$GITHUB_TOKEN" || echo "No GitHub token found"
install:
  - test -n "$TRAVIS_PHP_VERSION" && composer install --no-interaction --prefer-dist
  - test -n "$TRAVIS_NODE_VERSION" && npm install

before_script:
  -  test -n "$TRAVIS_PHP_VERSION" && phpcs --config-set installed_paths vendor/magento-ecg/coding-standard,vendor/magento/marketplace-eqp
script:
  - if [[ "$TEST_SUITE" == "editorconfig" ]]; git ls-files | xargs `npm bin`/editorconfig-tools check ; fi
  - if [[ "$TEST_SUITE" == "marketplace_review" ]]; phpcs ./ --ignore=./vendor --standard="MEQP1" --severity="10" --extensions=phtml,php,js,css ; fi
