<?php
/**
 * Copyright ePay | Dit Online Betalingssystem, (c) 2010.
 * 
 * This program is free software. You are allowed to use the software but NOT allowed to modify the software. 
 * It is also not legal to do any changes to the software and distribute it in your own name / brand. 
 */
?>
<fieldset class="form-list">
  <?php $_code=$this->getMethodCode() ?>
  <ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li><?php echo $this->__('EPAY_LABEL_2')?></li>
    <li><?php echo $this->getPaymentLogos()?></li>
  </ul>
</fieldset>

