<?php
/**
 * Copyright ePay | Dit Online Betalingssystem, (c) 2016.
 * 
 * This program is free software. You are allowed to use the software but NOT allowed to modify the software. 
 * It is also not legal to do any changes to the software and distribute it in your own name / brand. 
 */
?>
<div>
  <script type="text/javascript">
    var isPaymentWindowReady = false;

    function PaymentWindowReady()
    {
    paymentwindow = new PaymentWindow({
    <?php echo $this->getPaymentRequestString();?>
    });

    isPaymentWindowReady = true;
    }
  </script>
  <script type="text/javascript" src="https://ssl.ditonlinebetalingssystem.dk/integration/ewindow/paymentwindow.js" charset="UTF-8"></script>
  <script type="text/javascript">
    var timerOpenWindow;

    function openPaymentWindow()
    {
      if(isPaymentWindowReady)
      {
        clearInterval(timerOpenWindow);
        paymentwindow.open();
      }
    }

    document.onreadystatechange = function () {
      if (document.readyState === 'complete') {
        timerOpenWindow = setInterval('openPaymentWindow()', 500);
      }
    }
  </script>
  <h1>
    <?php echo $this->__("Payment") ?>
  </h1>
  <?php echo $this->__("To complete your order, you must now pay online. This is done through ePay online payment system (www.epay.eu).") ?>
  <br />
  <br />
  <table border="0">
    <tr>
      <td>
        <label for="Orderid">
          <?php echo $this->__("Order number") ?> :
        </label>
      </td>
      <td>
        <label for="Orderid">
          <?php echo $this->getOrderId() ?>
        </label>
      </td>
    </tr>
    <tr>
      <td>
        <label for="Amount">
          <?php echo $this->__("Amount") ?> :
        </label>
      </td>
      <td>
        <label for="CurrencyAmount">
          <?php echo $this->getCurrencyCode() ?>&nbsp;<?php echo $this->getFormattedAmount() ?>
        </label>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <br/>
        <?php echo $this->getLoadAction()?>
        <br/>
        <br/>
        <br/>
        <?php echo $this->__("If the Standard Payment Window does not open up automatically, click the button to activate the.") ?>
        <br/>
        <br/>
        <br/>
        <?php echo $this->getCancelAction()?>
      </td>
    </tr>
  </table>
</div>